#!/bin/bash
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:bitcoin/bitcoin -y
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils -y
sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb++-dev libminiupnpc-dev git -y 
sudo apt-get install libdb4.8-dev libdb4.8++-dev libqrencode-dev -y
cd ~/
git clone https://github.com/SimplicityDev2018/Simplicity.git
cd ~/Simplicity/src/secp256k1
chmod +x autogen.sh
sudo ./autogen.sh
sudo ./configure
sudo make && make install
cd ~/Simplicity/src/leveldb
sudo sh build_detect_platform build_config.mk .
cd ~/Simplicity/src/
sudo make -f makefile.unix
strip simplicityd
sudo cp -s /root/Simplicity/src/simplicityd /usr/bin/simplicityd
LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH
