#ifndef CHAINPARAMSSEEDS_H
#define CHAINPARAMSSEEDS_H
// List of fixed seed nodes for the bitcoin network
// AUTOGENERATED by contrib/devtools/generate-seeds.py

// Each line contains a 16-byte IPv6 address and a port.
// IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
static const unsigned int pnSeed[] =
{
	0x35b6de48, 0x3458767E, 0x340AC097, 0x77210F12, 0x0D7F8A5A, 0x90CA2BE3, 0x77210F12, 0x48DEB635, 
	0xB24AC181, 0x5B976FFA, 0x5E3E72CA
};


static const unsigned int pnTestnetSeed[] = {

};
#endif
